-- DROP TABLE IF EXISTS `user`;

-- # CREATE TABLE `board` (
-- #   `id` long NOT NULL,
-- #   `channelId` varchar(128) NOT NULL,
-- #   `name` varchar(20) DEFAULT NULL,
-- #   `nickname` varchar(50) DEFAULT NULL,
-- #   `password` varchar(128) DEFAULT NULL,
-- #   `create_date` datetime DEFAULT current_timestamp(),
-- #   PRIMARY KEY (`uid`),
-- #   UNIQUE KEY `user_idx_unique_email` (`email`)
-- # ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- #
-- # insert into user(uid, email, name, nickname, password) values('1', 'test@test.com', 'test_name', 'test_nick', '1234');
-- # insert into user(uid, email, name, nickname, password) values('2', 'test2@test.com', 'test2_name', 'test2_nick', 'test1234');
-- #

-- GRANT CREATE PUBLIC DATABASE LINK TO root;
-- CREATE DATABASE LINK TLINK CONNECT TO root IDENTIFIED BY djfflqjem1! USING
--     '(DESCRIPTION =
--       (ADDRESS_LIST =
--         (ADDRESS =
--           (PROTOCOL = TCP)
--           (HOST = 192.168.14.65)
--           (PORT = 9004)
--         )
--       )
--       (CONNECT_DATA =
--         (SERVICE_NAME = AUTH)
--       }
--     )';
--
-- CREATE DATABASE `board`
-- SELECT * FROM user@TLINK;
-- CREATE TABLE 'member' (
--     `id` long NOT null,
--     `role` varchar(50), NOT NULL,
--     `create_date` datetime DEFAULT current_timestamp(),
--     `attendance` int DEFAULT `0`,
--     `user_id` int NOT NULL,
--     PRIMARY KEY (`id`),
--     CONSTRAINT user_user_id uid_fk ,
--     FOREIGN KEY `user_id`,
--     REFERENCES user (user_id)
-- )