spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jwbae0820@gmail.com
    password: wyslqxfkpihydcql
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
